package akkoro:jwt;

interface decoder {
    enum jwt-error {
        invalid-token,
        invalid-jwks,
    }

    record validation-params {
        iss: string,
        aud: string,
    }

    record verify-result {
        valid: bool,
    }

    decode-verify: func(token: string, jwks: string, params: validation-params) -> result<verify-result, jwt-error>;
}

world jwt {
    import decoder;
}
