interface opa-module {
    enum policy-error {
        invalid-wasm,
        no-entrypoint,
    }

    record policy {
        id: string,
        entrypoints: list<string>,
    }

    new-policy: func(bytes: list<u8>) -> result<policy, policy-error>
    eval: func(policy: policy, data: string, input: string) -> bool
}

default world opa {
   import opa: self.opa-module 
}
