[workspace]
members = [
    "runtimes/aws-lambda/host",
    "runtimes/aws-lambda/guest",
    "runtimes/hyper",
#    "runtimes/kubelet",
#    "runtimes/openfaas",
#    "builtin/functions/verify-macaroon",
    "core",
    "core/guest",
    "core/guest/macros",
    "core/iomod",
    "core/iomod/guest",
    "core/io",
    "core/io/guest",
    "core/io/common",
    "cli",
#     "ayo-test/services/ayo-service/ayo-function"
]
exclude = ["examples"]
