package akkoro:secrets;

/// Provides interface to a secrets store
interface secret-storage {
    // TODO this should be a capability handle or `resource`
    type key = string;

    record secret {
        id: string,
        value: option<list<u8>>,
        // TODO metadata and caps
    }

    /// Return the secret value associated with the handle
    get-secret-value: func(id: string) -> result<secret, error>;

    /// Set the secret value associated with the handle
    set-secret-value: func(id: string, value: list<u8>, key: key) -> result<secret, error>;

    enum error {
        success,
        invalid-argument,
        forbidden
    }
}

world secrets {
    import secret-storage;
}
