[package]
name = "assemblylift-awslambda-host"
version = "0.4.0-beta.0"
description = "AssemblyLift AWS Lambda runtime"
authors = ["Akkoro and the AssemblyLift contributors <assemblylift@akkoro.io>"]
edition = "2018"
license-file = "../../../LICENSE.md"
repository = "https://github.com/akkoro/assemblylift"
readme = "README.md"

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "3.0", features = ["cargo"] }
crossbeam-channel = "0.5"
reqwest = { version = "0.11", features = ["blocking"] }
once_cell = "1.4"
toml = "0.5"
tokio = { version = "1.4", features = ["macros", "sync", "rt", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.3"
zip = "0.6"

assemblylift_core = { version = "0.4.0-beta.0", package = "assemblylift-core", path = "../../../core" }
assemblylift_core_iomod = { version = "0.4.0-beta.0", package = "assemblylift-core-iomod", path = "../../../core/iomod" }
assemblylift-wasi-secrets-in-memory = { path = "../../../runtimes/components/wasi-secrets/in-memory" }
